### ISSUE TITLE
[Umbrella] Engine refactoring

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1008]
Topics to be considered:

* ~Remove deltas~- will be fixed later, not as a part of this umbrella
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/500, https://github.com/ckeditor/ckeditor5-engine/issues/1162
* [x] Simplify the `change` event and batch API
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/679
* ~Merge controllers~
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/678
* [x] One API to rule them all
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/858, https://github.com/ckeditor/ckeditor5-engine/issues/738, https://github.com/ckeditor/ckeditor5-engine/issues/1186, https://github.com/ckeditor/ckeditor5-engine/issues/1209, https://github.com/ckeditor/ckeditor5-engine/issues/1210
* [x] Get rid of `enqueueChanges()` / Post-fixer API
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/654, https://github.com/ckeditor/ckeditor5-engine/issues/1101, https://github.com/ckeditor/ckeditor5-engine/issues/1207
* [x] Markers are all you need
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/1086
* [x] Schema improvements
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/532
* [x] Conversion improvements
    * Tickets: [Epic](https://github.com/ckeditor/ckeditor5-engine/issues/1172) (https://github.com/ckeditor/ckeditor5-engine/issues/829, https://github.com/ckeditor/ckeditor5-engine/issues/736, https://github.com/ckeditor/ckeditor5-engine/issues/778, https://github.com/ckeditor/ckeditor5-engine/issues/779, https://github.com/ckeditor/ckeditor5-engine/issues/945, https://github.com/ckeditor/ckeditor5-engine/issues/1214)
* ~Reduce memory pressure by stopping cloning all the time~
    * Tickets: https://github.com/ckeditor/ckeditor5-engine/issues/897

**Comment by scofalik** [comment]
We were talking about making conversion on `changesDone` event. I can't find exact issue or even if we finally all agreed this is a good idea. Here is the issue I found: https://github.com/ckeditor/ckeditor5-engine/issues/829

**Comment by Reinmar** [comment]
I also think that https://github.com/ckeditor/ckeditor5-engine/issues/897 (stop cloning everything, enforced immutability) is a part of this.

**Comment by pjasiun** [comment]
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/654 enqueueChanges() refactoring

**Comment by pjasiun** [comment]
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/1086 Markers are all you need

**Comment by pjasiun** [comment]
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/1101 Postfixing should be simpler

**Comment by pjasiun** [comment]
[ ] https://github.com/ckeditor/ckeditor5-engine/issues/532 Schema improvements

**Comment by Reinmar** [comment]
I'll add https://github.com/ckeditor/ckeditor5-engine/issues/1038 cause it grew to a significant problem and it turns out that it's not a quick and invisible change too (@scofalik can tell you more).

**Comment by scofalik** [comment]
I know that we have this: "#500 Introduce ModelDocument.applyDelta"

Buuut....

As time passes and more issues pop out, I started to have a feeling, that deltas were not a good idea. They are much harder to manage than we originally thought. They gave as good, fast start and hopes that we can easily solve some issues (like add row x add column conflict). 

Unfortunately, they have very real drawbacks:
 - transformation algorithms are much more complicated,
 - transformation bugs are more difficult to track,
 - special cases for delta transformations have to account that deltas may be in weird states,
 - some special cases are very difficult / impossible to solve when deltas are composed from operations without having their own logic.

Of course, we need to remember, that:
 - before we decide for such radical refactor, we need to test whether operations will fit all the goals we have, for example -- hypothetical `SplitOperation` may be need to transformed to `MoveOperation` -- we lose some information and it might lead to some "impossible to solve scenarios" too,
 - if we decide for such refactoring, it will take probably a couple of week to make initial re-write and then probably like two months to test and stabilize everything
 - we will need to write transformations for all new operations pairs.

All in all, I think that if operations will be enough to reach our goals, it would be a HUGE relief to get rid of deltas. It will have highly positive impact to the project's complexity and future maintaining.

**Comment by Reinmar** [comment]
> if we decide for such refactoring, it will take probably 2-3 weeks to make initial re-write and then probably like two months to test and stabilize everything,

Wonderful :D

> before we decide for such radical refactor, we need to test whether operations will fit all the goals we have

I think that we should not even think about reducing the number of types of changes at this point. If we have 10 deltas we need to have 10 operations after this change. So for all deltas which don't have operations yet, we need to create new operations.

This, in fact, may make it easier to quickly roll out an initial version of this refactoring. First, we'd get rid of deltas initially and move their transformations to operations. Then, we might think on how to improve this internally. Doing this step by step may be a lot easier.

**Comment by scofalik** [comment]
+1 for doing this step by step. Creating operations for all deltas and moving transformation to those operations will enable us to initially test new solution, without rebuilding the whole architecture.

**Comment by pjasiun** [comment]
Guys, please don't start discussions here. It is the umbrella ticket to keep all refactoring related tickets together. Otherwise, we will have to scan discussions to find tickets. Add a ticket, or not, there is no try.

**Comment by pjasiun** [comment]
Finally!
